// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using DataExportSales.Models;
using Newtonsoft.Json.Linq;

namespace DataExportSales.Models
{
    public static partial class DiscoverResponseCollection
    {
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public static IList<DiscoverResponse> DeserializeJson(JToken inputObject)
        {
            IList<DiscoverResponse> deserializedObject = new List<DiscoverResponse>();
            foreach (JToken iListValue in ((JArray)inputObject))
            {
                DiscoverResponse discoverResponse = new DiscoverResponse();
                discoverResponse.DeserializeJson(iListValue);
                deserializedObject.Add(discoverResponse);
            }
            return deserializedObject;
        }
    }
}
