// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace DataExportSales.Models
{
    public partial class EntityResponse
    {
        private string _displayName;
        
        /// <summary>
        /// Optional. Display name
        /// </summary>
        public string DisplayName
        {
            get { return this._displayName; }
            set { this._displayName = value; }
        }
        
        private string _logicalName;
        
        /// <summary>
        /// Optional. Logical name
        /// </summary>
        public string LogicalName
        {
            get { return this._logicalName; }
            set { this._logicalName = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the EntityResponse class.
        /// </summary>
        public EntityResponse()
        {
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken displayNameValue = inputObject["DisplayName"];
                if (displayNameValue != null && displayNameValue.Type != JTokenType.Null)
                {
                    this.DisplayName = ((string)displayNameValue);
                }
                JToken logicalNameValue = inputObject["LogicalName"];
                if (logicalNameValue != null && logicalNameValue.Type != JTokenType.Null)
                {
                    this.LogicalName = ((string)logicalNameValue);
                }
            }
        }
    }
}
