// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace DataExportSales.Models
{
    public partial class EntityExportStatusDescription
    {
        private string _entityMetadataState;
        
        /// <summary>
        /// Optional. Detailed state
        /// </summary>
        public string EntityMetadataState
        {
            get { return this._entityMetadataState; }
            set { this._entityMetadataState = value; }
        }
        
        private long? _failureNotifications;
        
        /// <summary>
        /// Optional. Failure notification count
        /// </summary>
        public long? FailureNotifications
        {
            get { return this._failureNotifications; }
            set { this._failureNotifications = value; }
        }
        
        private string _initialSyncState;
        
        /// <summary>
        /// Optional. Get or Sets the detailed InitialSync State
        /// </summary>
        public string InitialSyncState
        {
            get { return this._initialSyncState; }
            set { this._initialSyncState = value; }
        }
        
        private DateTimeOffset? _lastExportDate;
        
        /// <summary>
        /// Optional. Last export date
        /// </summary>
        public DateTimeOffset? LastExportDate
        {
            get { return this._lastExportDate; }
            set { this._lastExportDate = value; }
        }
        
        private string _lastExportStatus;
        
        /// <summary>
        /// Optional. Last export status
        /// </summary>
        public string LastExportStatus
        {
            get { return this._lastExportStatus; }
            set { this._lastExportStatus = value; }
        }
        
        private string _profileId;
        
        /// <summary>
        /// Optional. Profile Id
        /// </summary>
        public string ProfileId
        {
            get { return this._profileId; }
            set { this._profileId = value; }
        }
        
        private long? _successNotifications;
        
        /// <summary>
        /// Optional. Successful notification count
        /// </summary>
        public long? SuccessNotifications
        {
            get { return this._successNotifications; }
            set { this._successNotifications = value; }
        }
        
        private long? _totalNotifications;
        
        /// <summary>
        /// Optional. Total notification count
        /// </summary>
        public long? TotalNotifications
        {
            get { return this._totalNotifications; }
            set { this._totalNotifications = value; }
        }
        
        private string _type;
        
        /// <summary>
        /// Optional. Entity type
        /// </summary>
        public string Type
        {
            get { return this._type; }
            set { this._type = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the EntityExportStatusDescription
        /// class.
        /// </summary>
        public EntityExportStatusDescription()
        {
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken entityMetadataStateValue = inputObject["EntityMetadataState"];
                if (entityMetadataStateValue != null && entityMetadataStateValue.Type != JTokenType.Null)
                {
                    this.EntityMetadataState = ((string)entityMetadataStateValue);
                }
                JToken failureNotificationsValue = inputObject["FailureNotifications"];
                if (failureNotificationsValue != null && failureNotificationsValue.Type != JTokenType.Null)
                {
                    this.FailureNotifications = ((long)failureNotificationsValue);
                }
                JToken initialSyncStateValue = inputObject["InitialSyncState"];
                if (initialSyncStateValue != null && initialSyncStateValue.Type != JTokenType.Null)
                {
                    this.InitialSyncState = ((string)initialSyncStateValue);
                }
                JToken lastExportDateValue = inputObject["LastExportDate"];
                if (lastExportDateValue != null && lastExportDateValue.Type != JTokenType.Null)
                {
                    this.LastExportDate = ((DateTimeOffset)lastExportDateValue);
                }
                JToken lastExportStatusValue = inputObject["LastExportStatus"];
                if (lastExportStatusValue != null && lastExportStatusValue.Type != JTokenType.Null)
                {
                    this.LastExportStatus = ((string)lastExportStatusValue);
                }
                JToken profileIdValue = inputObject["ProfileId"];
                if (profileIdValue != null && profileIdValue.Type != JTokenType.Null)
                {
                    this.ProfileId = ((string)profileIdValue);
                }
                JToken successNotificationsValue = inputObject["SuccessNotifications"];
                if (successNotificationsValue != null && successNotificationsValue.Type != JTokenType.Null)
                {
                    this.SuccessNotifications = ((long)successNotificationsValue);
                }
                JToken totalNotificationsValue = inputObject["TotalNotifications"];
                if (totalNotificationsValue != null && totalNotificationsValue.Type != JTokenType.Null)
                {
                    this.TotalNotifications = ((long)totalNotificationsValue);
                }
                JToken typeValue = inputObject["Type"];
                if (typeValue != null && typeValue.Type != JTokenType.Null)
                {
                    this.Type = ((string)typeValue);
                }
            }
        }
        
        /// <summary>
        /// Serialize the object
        /// </summary>
        /// <returns>
        /// Returns the json model for the type EntityExportStatusDescription
        /// </returns>
        public virtual JToken SerializeJson(JToken outputObject)
        {
            if (outputObject == null)
            {
                outputObject = new JObject();
            }
            if (this.EntityMetadataState != null)
            {
                outputObject["EntityMetadataState"] = this.EntityMetadataState;
            }
            if (this.FailureNotifications != null)
            {
                outputObject["FailureNotifications"] = this.FailureNotifications.Value;
            }
            if (this.InitialSyncState != null)
            {
                outputObject["InitialSyncState"] = this.InitialSyncState;
            }
            if (this.LastExportDate != null)
            {
                outputObject["LastExportDate"] = this.LastExportDate.Value;
            }
            if (this.LastExportStatus != null)
            {
                outputObject["LastExportStatus"] = this.LastExportStatus;
            }
            if (this.ProfileId != null)
            {
                outputObject["ProfileId"] = this.ProfileId;
            }
            if (this.SuccessNotifications != null)
            {
                outputObject["SuccessNotifications"] = this.SuccessNotifications.Value;
            }
            if (this.TotalNotifications != null)
            {
                outputObject["TotalNotifications"] = this.TotalNotifications.Value;
            }
            if (this.Type != null)
            {
                outputObject["Type"] = this.Type;
            }
            return outputObject;
        }
    }
}
