// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using DataExportSales.Models;
using Microsoft.Rest;
using Newtonsoft.Json.Linq;

namespace DataExportSales.Models
{
    public partial class ProfileDescriptionBase
    {
        private string _destinationKeyVaultUri;
        
        /// <summary>
        /// Optional. Destination KeyVault URI
        /// </summary>
        public string DestinationKeyVaultUri
        {
            get { return this._destinationKeyVaultUri; }
            set { this._destinationKeyVaultUri = value; }
        }
        
        private string _destinationPrefix;
        
        /// <summary>
        /// Optional. Destination prefix
        /// </summary>
        public string DestinationPrefix
        {
            get { return this._destinationPrefix; }
            set { this._destinationPrefix = value; }
        }
        
        private string _destinationSchemaName;
        
        /// <summary>
        /// Optional. Destination schema name
        /// </summary>
        public string DestinationSchemaName
        {
            get { return this._destinationSchemaName; }
            set { this._destinationSchemaName = value; }
        }
        
        private string _destinationType;
        
        /// <summary>
        /// Optional. Destination type
        /// </summary>
        public string DestinationType
        {
            get { return this._destinationType; }
            set { this._destinationType = value; }
        }
        
        private IList<EntityDescription> _entities;
        
        /// <summary>
        /// Optional. Entities
        /// </summary>
        public IList<EntityDescription> Entities
        {
            get { return this._entities; }
            set { this._entities = value; }
        }
        
        private string _name;
        
        /// <summary>
        /// Optional. Name
        /// </summary>
        public string Name
        {
            get { return this._name; }
            set { this._name = value; }
        }
        
        private string _organizationId;
        
        /// <summary>
        /// Optional. Organization Id
        /// </summary>
        public string OrganizationId
        {
            get { return this._organizationId; }
            set { this._organizationId = value; }
        }
        
        private RetryPolicyDescription _retryPolicy;
        
        /// <summary>
        /// Optional. Retry policy
        /// </summary>
        public RetryPolicyDescription RetryPolicy
        {
            get { return this._retryPolicy; }
            set { this._retryPolicy = value; }
        }
        
        private bool? _writeDeleteLog;
        
        /// <summary>
        /// Optional. Should write to delete log
        /// </summary>
        public bool? WriteDeleteLog
        {
            get { return this._writeDeleteLog; }
            set { this._writeDeleteLog = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the ProfileDescriptionBase class.
        /// </summary>
        public ProfileDescriptionBase()
        {
            this.Entities = new LazyList<EntityDescription>();
        }
        
        /// <summary>
        /// Serialize the object
        /// </summary>
        /// <returns>
        /// Returns the json model for the type ProfileDescriptionBase
        /// </returns>
        public virtual JToken SerializeJson(JToken outputObject)
        {
            if (outputObject == null)
            {
                outputObject = new JObject();
            }
            if (this.DestinationKeyVaultUri != null)
            {
                outputObject["DestinationKeyVaultUri"] = this.DestinationKeyVaultUri;
            }
            if (this.DestinationPrefix != null)
            {
                outputObject["DestinationPrefix"] = this.DestinationPrefix;
            }
            if (this.DestinationSchemaName != null)
            {
                outputObject["DestinationSchemaName"] = this.DestinationSchemaName;
            }
            if (this.DestinationType != null)
            {
                outputObject["DestinationType"] = this.DestinationType;
            }
            JArray entitiesSequence = null;
            if (this.Entities != null)
            {
                if (this.Entities is ILazyCollection<EntityDescription> == false || ((ILazyCollection<EntityDescription>)this.Entities).IsInitialized)
                {
                    entitiesSequence = new JArray();
                    outputObject["Entities"] = entitiesSequence;
                    foreach (EntityDescription entitiesItem in this.Entities)
                    {
                        if (entitiesItem != null)
                        {
                            entitiesSequence.Add(entitiesItem.SerializeJson(null));
                        }
                    }
                }
            }
            if (this.Name != null)
            {
                outputObject["Name"] = this.Name;
            }
            if (this.OrganizationId != null)
            {
                outputObject["OrganizationId"] = this.OrganizationId;
            }
            if (this.RetryPolicy != null)
            {
                outputObject["RetryPolicy"] = this.RetryPolicy.SerializeJson(null);
            }
            if (this.WriteDeleteLog != null)
            {
                outputObject["WriteDeleteLog"] = this.WriteDeleteLog.Value;
            }
            return outputObject;
        }
    }
}
