// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace DataExportSales.Models
{
    public partial class ConnectorDetailResponse
    {
        private string _connectorUrl;
        
        /// <summary>
        /// Optional. Connector URL
        /// </summary>
        public string ConnectorUrl
        {
            get { return this._connectorUrl; }
            set { this._connectorUrl = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the ConnectorDetailResponse class.
        /// </summary>
        public ConnectorDetailResponse()
        {
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken connectorUrlValue = inputObject["ConnectorUrl"];
                if (connectorUrlValue != null && connectorUrlValue.Type != JTokenType.Null)
                {
                    this.ConnectorUrl = ((string)connectorUrlValue);
                }
            }
        }
    }
}
