// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Rest;
using Newtonsoft.Json.Linq;

namespace DataExportSales.Models
{
    public partial class ErrorResponse
    {
        private string _correlationId;
        
        /// <summary>
        /// Optional. Correlation Id
        /// </summary>
        public string CorrelationId
        {
            get { return this._correlationId; }
            set { this._correlationId = value; }
        }
        
        private string _details;
        
        /// <summary>
        /// Optional. Details
        /// </summary>
        public string Details
        {
            get { return this._details; }
            set { this._details = value; }
        }
        
        private string _errorCode;
        
        /// <summary>
        /// Optional. Error Code
        /// </summary>
        public string ErrorCode
        {
            get { return this._errorCode; }
            set { this._errorCode = value; }
        }
        
        private string _message;
        
        /// <summary>
        /// Optional. Message
        /// </summary>
        public string Message
        {
            get { return this._message; }
            set { this._message = value; }
        }
        
        private IList<string> _parameters;
        
        /// <summary>
        /// Optional. Parameters
        /// </summary>
        public IList<string> Parameters
        {
            get { return this._parameters; }
            set { this._parameters = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the ErrorResponse class.
        /// </summary>
        public ErrorResponse()
        {
            this.Parameters = new LazyList<string>();
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken correlationIdValue = inputObject["CorrelationId"];
                if (correlationIdValue != null && correlationIdValue.Type != JTokenType.Null)
                {
                    this.CorrelationId = ((string)correlationIdValue);
                }
                JToken detailsValue = inputObject["Details"];
                if (detailsValue != null && detailsValue.Type != JTokenType.Null)
                {
                    this.Details = ((string)detailsValue);
                }
                JToken errorCodeValue = inputObject["ErrorCode"];
                if (errorCodeValue != null && errorCodeValue.Type != JTokenType.Null)
                {
                    this.ErrorCode = ((string)errorCodeValue);
                }
                JToken messageValue = inputObject["Message"];
                if (messageValue != null && messageValue.Type != JTokenType.Null)
                {
                    this.Message = ((string)messageValue);
                }
                JToken parametersSequence = ((JToken)inputObject["Parameters"]);
                if (parametersSequence != null && parametersSequence.Type != JTokenType.Null)
                {
                    foreach (JToken parametersValue in ((JArray)parametersSequence))
                    {
                        this.Parameters.Add(((string)parametersValue));
                    }
                }
            }
        }
    }
}
