// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace DataExportSales.Models
{
    public partial class ProfileStatus
    {
        private string _exportStatus;
        
        /// <summary>
        /// Optional. Export status
        /// </summary>
        public string ExportStatus
        {
            get { return this._exportStatus; }
            set { this._exportStatus = value; }
        }
        
        private long? _failureNotifications;
        
        /// <summary>
        /// Optional. Failure notification count
        /// </summary>
        public long? FailureNotifications
        {
            get { return this._failureNotifications; }
            set { this._failureNotifications = value; }
        }
        
        private string _initialSyncState;
        
        /// <summary>
        /// Optional. Initial Sync State.
        /// </summary>
        public string InitialSyncState
        {
            get { return this._initialSyncState; }
            set { this._initialSyncState = value; }
        }
        
        private DateTimeOffset? _lastExportDate;
        
        /// <summary>
        /// Optional. Last export date
        /// </summary>
        public DateTimeOffset? LastExportDate
        {
            get { return this._lastExportDate; }
            set { this._lastExportDate = value; }
        }
        
        private DateTimeOffset? _lastModifiedOn;
        
        /// <summary>
        /// Optional. Last modified on
        /// </summary>
        public DateTimeOffset? LastModifiedOn
        {
            get { return this._lastModifiedOn; }
            set { this._lastModifiedOn = value; }
        }
        
        private string _metadataState;
        
        /// <summary>
        /// Optional. Detailed state
        /// </summary>
        public string MetadataState
        {
            get { return this._metadataState; }
            set { this._metadataState = value; }
        }
        
        private long? _successNotifications;
        
        /// <summary>
        /// Optional. Successful notification count
        /// </summary>
        public long? SuccessNotifications
        {
            get { return this._successNotifications; }
            set { this._successNotifications = value; }
        }
        
        private long? _totalNotifications;
        
        /// <summary>
        /// Optional. Total notification count
        /// </summary>
        public long? TotalNotifications
        {
            get { return this._totalNotifications; }
            set { this._totalNotifications = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the ProfileStatus class.
        /// </summary>
        public ProfileStatus()
        {
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken exportStatusValue = inputObject["ExportStatus"];
                if (exportStatusValue != null && exportStatusValue.Type != JTokenType.Null)
                {
                    this.ExportStatus = ((string)exportStatusValue);
                }
                JToken failureNotificationsValue = inputObject["FailureNotifications"];
                if (failureNotificationsValue != null && failureNotificationsValue.Type != JTokenType.Null)
                {
                    this.FailureNotifications = ((long)failureNotificationsValue);
                }
                JToken initialSyncStateValue = inputObject["InitialSyncState"];
                if (initialSyncStateValue != null && initialSyncStateValue.Type != JTokenType.Null)
                {
                    this.InitialSyncState = ((string)initialSyncStateValue);
                }
                JToken lastExportDateValue = inputObject["LastExportDate"];
                if (lastExportDateValue != null && lastExportDateValue.Type != JTokenType.Null)
                {
                    this.LastExportDate = ((DateTimeOffset)lastExportDateValue);
                }
                JToken lastModifiedOnValue = inputObject["LastModifiedOn"];
                if (lastModifiedOnValue != null && lastModifiedOnValue.Type != JTokenType.Null)
                {
                    this.LastModifiedOn = ((DateTimeOffset)lastModifiedOnValue);
                }
                JToken metadataStateValue = inputObject["MetadataState"];
                if (metadataStateValue != null && metadataStateValue.Type != JTokenType.Null)
                {
                    this.MetadataState = ((string)metadataStateValue);
                }
                JToken successNotificationsValue = inputObject["SuccessNotifications"];
                if (successNotificationsValue != null && successNotificationsValue.Type != JTokenType.Null)
                {
                    this.SuccessNotifications = ((long)successNotificationsValue);
                }
                JToken totalNotificationsValue = inputObject["TotalNotifications"];
                if (totalNotificationsValue != null && totalNotificationsValue.Type != JTokenType.Null)
                {
                    this.TotalNotifications = ((long)totalNotificationsValue);
                }
            }
        }
        
        /// <summary>
        /// Serialize the object
        /// </summary>
        /// <returns>
        /// Returns the json model for the type ProfileStatus
        /// </returns>
        public virtual JToken SerializeJson(JToken outputObject)
        {
            if (outputObject == null)
            {
                outputObject = new JObject();
            }
            if (this.ExportStatus != null)
            {
                outputObject["ExportStatus"] = this.ExportStatus;
            }
            if (this.FailureNotifications != null)
            {
                outputObject["FailureNotifications"] = this.FailureNotifications.Value;
            }
            if (this.InitialSyncState != null)
            {
                outputObject["InitialSyncState"] = this.InitialSyncState;
            }
            if (this.LastExportDate != null)
            {
                outputObject["LastExportDate"] = this.LastExportDate.Value;
            }
            if (this.LastModifiedOn != null)
            {
                outputObject["LastModifiedOn"] = this.LastModifiedOn.Value;
            }
            if (this.MetadataState != null)
            {
                outputObject["MetadataState"] = this.MetadataState;
            }
            if (this.SuccessNotifications != null)
            {
                outputObject["SuccessNotifications"] = this.SuccessNotifications.Value;
            }
            if (this.TotalNotifications != null)
            {
                outputObject["TotalNotifications"] = this.TotalNotifications.Value;
            }
            return outputObject;
        }
    }
}
