// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using DataExportSales.Models;
using Newtonsoft.Json.Linq;

namespace DataExportSales.Models
{
    public static partial class ProfileDetailsDTOCollection
    {
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public static IList<ProfileDetailsDTO> DeserializeJson(JToken inputObject)
        {
            IList<ProfileDetailsDTO> deserializedObject = new List<ProfileDetailsDTO>();
            foreach (JToken iListValue in ((JArray)inputObject))
            {
                ProfileDetailsDTO profileDetailsDTO = new ProfileDetailsDTO();
                profileDetailsDTO.DeserializeJson(iListValue);
                deserializedObject.Add(profileDetailsDTO);
            }
            return deserializedObject;
        }
    }
}
